### PR TITLE
Re-release notils with jdoc and source

### PR DESCRIPTION
**Pull request by ataulm**
Not really much to PR, but I've been burned by pushing these on master before!

### CODE REVIEW

**Comment by blundell** [comment]
:+1: no need for PR's tbh. Do you see a value? Suppose it's a record of releases

**Comment by ataulm** [comment]
no value for reading, but slowing down the release process gives me time to remember "oh crap, I forgot X"

**Comment by blundell** [comment]
how slow!

**Comment by blundell** [comment]
:tongue:

**Pull request merged**
